name: publish mailcheck nuget 

on:
  push:
    tags:
    - "mailcheck-[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/mailcheck-/}" >> $GITHUB_ENV
      - name: Notify Slack Start
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: package-builds
          status: STARTING
          color: warning

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release  --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
      - name: Pack
        run: dotnet pack --configuration Release FishAngler.MailCheck /p:PackageVersion=${VERSION} --output .
      - name: Push
        run: dotnet nuget push FishAngler.MailCheck.${VERSION}.nupkg --source https://nuget.pkg.github.com/CraftJack/index.json --api-key ${GITHUB_TOKEN}

      - name: Notify Slack Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: package-builds
          status: SUCCESS
          color: good
      - name: Notify Slack Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: package-builds
          status: FAILURE
          color: danger